/**
 * Status Utilities
 * 
 * This file contains the core definitions and utilities for the video processing status system.
 * It defines the progression of statuses, their meanings, and utility functions.
 * 
 * Status Progression Flow:
 * 1. uploading    - Initial upload to Cloudflare
 * 2. queued       - Queued for processing in Cloudflare
 * 3. processing   - Being processed by Cloudflare
 * 4. stream_ready - Ready for streaming but MP4 not yet created
 * 5. waitformp4   - Waiting for MP4 to be generated by Cloudflare
 * 6. mp4downloading - Downloading MP4 file from Cloudflare
 * 7. r2_uploading - Uploading MP4 to R2 storage
 * 8. complete     - Processing complete, video available
 * 
 * Error state can occur at any point.
 */

import { createClient } from '@supabase/supabase-js';

// Initialize Supabase client for database operations
const supabase = createClient(
  process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

/**
 * Status order definition - determines valid progression paths
 * Higher numbers should come after lower numbers in the progression
 */
export const STATUS_ORDER = {
  'uploading': 1,     // Initial upload to Cloudflare
  'queued': 2,        // Queued for processing in Cloudflare
  'processing': 3,    // Processing by Cloudflare
  'stream_ready': 4,  // Ready for streaming but no MP4 yet
  'waitformp4': 5,    // Waiting for MP4 to be generated
  'mp4_processing': 6, // MP4 is being processed
  'mp4downloading': 7, // MP4 is being downloaded
  'r2_uploading': 8,   // Uploading to R2 storage
  'complete': 9,       // Processing complete
  'error': 10          // Error state (can happen at any point)
};

/**
 * Map from Cloudflare states to our internal states
 */
export const CLOUDFLARE_STATUS_MAPPING = {
  pendingupload: 'uploading',  // Initial upload to Cloudflare
  inprogress: 'processing',    // Cloudflare processing the video
  ready: 'stream_ready',       // Basic Cloudflare processing complete
  error: 'error',              // Processing error
};

/**
 * Get a human-readable status message for the current processing state
 * 
 * @param {string} status - The current status
 * @returns {string} Human-readable status message
 */
export function getStatusMessage(status) {
  switch (status) {
    case 'uploading':
      return 'Uploading video to Cloudflare...';
    case 'queued':
      return 'Queued for processing...';
    case 'processing':
      return 'Cloudflare is processing your video...';
    case 'stream_ready':
      return 'Preparing to create MP4 version...';
    case 'waitformp4':
      return 'Creating MP4 version...';
    case 'mp4_processing':
      return 'Processing MP4 file...';
    case 'mp4downloading':
      return 'Downloading MP4 file...';
    case 'r2_uploading':
      return 'Uploading to permanent storage...';
    case 'complete':
      return 'Processing complete';
    case 'error':
      return 'Error processing video';
    default:
      return 'Processing...';
  }
}

/**
 * Get the minimum progress percentage for a given status
 * This ensures progress never moves backward in the UI
 * 
 * @param {string} status - Processing status
 * @returns {number} Minimum progress percentage
 */
export function getMinProgressForStatus(status) {
  switch (status) {
    case 'uploading': return 15;
    case 'queued': return 30;
    case 'processing': return 50;
    case 'stream_ready': return 60;
    case 'waitformp4': return 70;
    case 'mp4_processing': return 75;
    case 'mp4downloading': return 85;
    case 'r2_uploading': return 95;
    case 'complete': return 100;
    case 'error': return 100; // Errors still show full progress bar
    default: return 0;
  }
}

/**
 * Check if a status transition is valid according to our status order
 * 
 * @param {string} currentStatus - Current status
 * @param {string} newStatus - New status to transition to
 * @returns {boolean} Whether the transition is valid
 */
export function isValidStatusTransition(currentStatus, newStatus) {
  // Null is not a valid status to transition to
  if (newStatus === null || newStatus === undefined) {
    return false;
  }
  
  // Error can always be set
  if (newStatus === 'error') return true;
  
  // Allow cycling between mp4_processing and waitformp4
  if (currentStatus === 'mp4_processing' && newStatus === 'waitformp4') return true;
  if (currentStatus === 'waitformp4' && newStatus === 'mp4_processing') return true;
  
  // For all other transitions, new status must be higher in order
  if (!STATUS_ORDER[currentStatus] || !STATUS_ORDER[newStatus]) return false;
  return STATUS_ORDER[newStatus] > STATUS_ORDER[currentStatus];
}

/**
 * Get video details from the clips table using the Cloudflare UID
 * 
 * @param {string} videoUid - Cloudflare video UID
 * @returns {Promise<Object>} Video data or null if not found
 */
export async function getVideoByCloudflareId(videoUid) {
  try {
    const { data, error } = await supabase
      .from('clips')
      .select('*')
      .eq('cloudflare_uid', videoUid)
      .single();
      
    if (error) {
      console.log(`Error fetching video with cloudflare_uid ${videoUid}: ${error.message}`);
      return null;
    }
    
    return data;
  } catch (error) {
    console.log(`Exception fetching video: ${error.message}`);
    return null;
  }
}

/**
 * Find all videos with requested status changes
 * 
 * @param {number} limit - Maximum number of videos to fetch
 * @returns {Promise<Array>} Array of videos with requested status changes
 */
export async function getVideosWithRequestedStatusChanges(limit = 10) {
  try {
    const { data, error } = await supabase
      .from('clips')
      .select('*')
      .not('requested_status', 'is', null)
      .order('uploaded_at', { ascending: true })
      .limit(limit);
      
    if (error) {
      console.log(`Error fetching videos with requested status changes: ${error.message}`);
      return [];
    }
    
    return data || [];
  } catch (error) {
    console.log(`Exception fetching videos with status changes: ${error.message}`);
    return [];
  }
} 